version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask

  flask:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    volumes:
      - ./back-end:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./back-end/.env