"""Add description column to Picture model

Revision ID: 495200463d0f
Revises: 96649af8b5c2
Create Date: 2024-03-12 16:33:08.514012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495200463d0f'
down_revision = '96649af8b5c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
