"""empty message

Revision ID: 765c8f6fb137
Revises: d79537a427fd
Create Date: 2023-12-14 15:46:32.413036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765c8f6fb137'
down_revision = 'd79537a427fd'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if "_alembic_tmp_user" in inspector.get_table_names():
        op.drop_table("_alembic_tmp_user")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False, server_default='default@example.com'))
        batch_op.create_unique_constraint('unique_user_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
