"""empty message

Revision ID: 96649af8b5c2
Revises: eca5afb59ab8
Create Date: 2023-12-18 14:53:59.537631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96649af8b5c2'
down_revision = 'eca5afb59ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('confirmation_token', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_confirmation_token', ['confirmation_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('confirmation_token')
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
