"""more words in description

Revision ID: c0afe2a908a0
Revises: 495200463d0f
Create Date: 2024-03-18 17:00:40.906265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0afe2a908a0'
down_revision = '495200463d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(length=500),
               type_=sa.Text(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(length=1000),
               type_=sa.TEXT(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
